version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
      time: "08:00"
      timezone: Asia/Kolkata
    rebase-strategy: "auto"
    open-pull-requests-limit: 2