name: Report Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Execute tests
        id: execute-tests
        run: mvn clean test -Pweb-tests -Drunmode=selenoid --no-transfer-progress

      - name: Deploy HTML Reports
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./reports

      - name: Upload Report
        if: steps.execute-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: Extent-Report
          path: ./reports
