#TODO: Make the 'Start Selenoid server' a seperate task based on the inputs of runmode.
name: Test Workflow Input

on:
  workflow_dispatch:
    inputs:
      mavenProfile:
        description: "Which maven profile to execute?"
        required: true
        default: "web-tests"
      runmode:
        description: "Where to run? browserstack or selenoid"
        options:
          - "selenoid"
          - "browserstack"
        required: true
        default: "selenoid"
        type: choice

env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome;firefox
          last-versions: 1

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status

      - name: checkout
        uses: actions/checkout@v3

      - name: Run the tests
        run: mvn clean test -P${{ github.event.inputs.mavenProfile }} -Drunmode=${{ github.event.inputs.runmode }} --no-transfer-progress
