name: Provide inputs in test workflow

on:
  workflow_dispatch:
    inputs:
      mavenProfile:
        description: "web or anyother"
        required: true
        default: "web-tests"
      gridurl:
        description: "selenoid url if hosted remote server"
        required: true
        default: "http://localhost:4444/wd/hub"
      runmode:
        description: "browserstack, selenoid"
        required: true
        default: "selenoid"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Selenoid server
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status

      - name: checkout
        uses: actions/checkout@v2

      - name: Run the tests
        continue-on-error: true
        run: mvn clean test -P${{ github.event.inputs.mavenProfile }} -DremoteURL=${{ github.event.inputs.gridurl }} -Dtarget=${{ github.event.inputs.runmode }}
